import React, { useState, useEffect, useCallback } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { Save, Download, Lightbulb, BookOpen, Copy, FileDown, Check, Scale, ExternalLink } from 'lucide-react';
import { jsPDF } from 'jspdf';
import api from '../utils/api';
import QualityScoreDashboard from '../components/QualityScoreDashboard';

const DraftEditor = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const [draft, setDraft] = useState(null);
  const [content, setContent] = useState('');
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [copied, setCopied] = useState(false);
  const [autoSaving, setAutoSaving] = useState(false);
  const [lastSaved, setLastSaved] = useState(null);
  const [selectedText, setSelectedText] = useState('');
  const [aiResult, setAiResult] = useState('');
  const [aiLoading, setAiLoading] = useState(false);
  const [showQuality, setShowQuality] = useState(true);
  const [caseLawResults, setCaseLawResults] = useState([]);
  const [caseLawLoading, setCaseLawLoading] = useState(false);
  const [showCaseLaw, setShowCaseLaw] = useState(false);

  const fetchDraft = useCallback(async () => {
    try {
      const response = await api.get(`/drafts/${id}`);
      setDraft(response.data);
      setContent(response.data.content);
    } catch (err) {
      console.error(err);
      alert('Failed to load draft');
      navigate('/dashboard');
    } finally {
      setLoading(false);
    }
  }, [id, navigate]);

  useEffect(() => {
    fetchDraft();
  }, [fetchDraft]);

  // Auto-save functionality - saves every 30 seconds
  useEffect(() => {
    if (!content || !draft) return;

    const autoSaveInterval = setInterval(async () => {
      setAutoSaving(true);
      try {
        await api.put(`/drafts/${id}`, content, {
          headers: { 'Content-Type': 'application/json' },
          params: { content }
        });
        setLastSaved(new Date());
      } catch (err) {
        console.error('Auto-save failed:', err);
      } finally {
        setAutoSaving(false);
      }
    }, 30000); // 30 seconds

    return () => clearInterval(autoSaveInterval);
  }, [content, draft, id]);

  const handleSave = async () => {
    setSaving(true);
    try {
      await api.put(`/drafts/${id}`, content, {
        headers: { 'Content-Type': 'application/json' },
        params: { content }
      });
      setLastSaved(new Date());
      alert('Draft saved successfully!');
    } catch (err) {
      alert('Failed to save draft');
    } finally {
      setSaving(false);
    }
  };

  const handleCopyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000); // Reset after 2 seconds
    } catch (err) {
      alert('Failed to copy to clipboard');
    }
  };

  const handleDownloadPDF = () => {
    try {
      const doc = new jsPDF();
      
      // Set document properties
      doc.setProperties({
        title: draft?.title || 'Legal Petition',
        subject: `${draft?.document_type} - ${draft?.case_type}`,
        author: 'LawMind AI',
        keywords: 'legal, petition, indian law',
        creator: 'LawMind - AI Legal Assistant'
      });

      // Add header
      doc.setFontSize(16);
      doc.setFont('helvetica', 'bold');
      doc.text(draft?.title || 'Legal Petition', 105, 20, { align: 'center' });
      
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text(`${draft?.document_type} | ${draft?.case_type}`, 105, 28, { align: 'center' });
      
      // Add line separator
      doc.setLineWidth(0.5);
      doc.line(20, 32, 190, 32);
      
      // Add content
      doc.setFontSize(11);
      doc.setFont('times', 'normal');
      
      // Split content into lines that fit page width
      const lines = doc.splitTextToSize(content, 170);
      let yPosition = 40;
      const pageHeight = doc.internal.pageSize.height;
      
      lines.forEach((line) => {
        if (yPosition > pageHeight - 20) {
          doc.addPage();
          yPosition = 20;
        }
        doc.text(line, 20, yPosition);
        yPosition += 6;
      });
      
      // Add footer on last page
      const pageCount = doc.internal.getNumberOfPages();
      doc.setPage(pageCount);
      doc.setFontSize(8);
      doc.setTextColor(128);
      doc.text('Generated by LawMind AI - Legal Petition Drafting Assistant', 105, pageHeight - 10, { align: 'center' });
      
      // Download PDF
      doc.save(`${draft?.title || 'petition'}.pdf`);
    } catch (err) {
      console.error('PDF generation error:', err);
      alert('Failed to generate PDF. Please try again.');
    }
  };

  const handleExport = async (format) => {
    try {
      await api.post('/documents/export', {
        draft_id: parseInt(id),
        format: format,
        include_watermark: true
      });
      alert(`Draft exported as ${format.toUpperCase()} successfully!`);
    } catch (err) {
      alert('Failed to export draft');
    }
  };

  const handleAiAction = async (action) => {
    setAiLoading(true);
    setAiResult('');
    
    try {
      const response = await api.post('/drafts/edit', {
        draft_id: parseInt(id),
        action: action,
        selected_text: selectedText || content,
        context: ''
      });

      if (response.data.suggestions) {
        setAiResult(response.data.suggestions.join('\n\n'));
      } else {
        setAiResult(response.data.result);
      }
      
      setShowQuality(false); // Switch to AI Assistant tab
    } catch (err) {
      alert('AI action failed');
    } finally {
      setAiLoading(false);
    }
  };

  const handleTextSelection = () => {
    const selection = window.getSelection().toString();
    if (selection) {
      setSelectedText(selection);
      setShowQuality(false); // Switch to AI Assistant tab
    }
  };

  // Case Law Search
  const searchCaseLaw = async () => {
    setCaseLawLoading(true);
    setShowCaseLaw(true);
    try {
      const searchQuery = `${draft?.case_type} ${draft?.sections || ''} ${content.substring(0, 200)}`;
      const response = await api.get('/drafts/case-law/search', {
        params: {
          query: searchQuery,
          max_results: 10,
          court: draft?.court,
          case_type: draft?.case_type
        }
      });
      setCaseLawResults(response.data.cases || []);
    } catch (err) {
      console.error('Case law search failed:', err);
      alert('Failed to search case law');
    } finally {
      setCaseLawLoading(false);
    }
  };

  const insertCitation = async (caseData) => {
    try {
      const citationText = `${caseData.title}, ${caseData.citation}`;
      const response = await api.post(`/drafts/drafts/${id}/insert-citation`, null, {
        params: {
          citation_text: citationText,
          position: 0
        }
      });
      setContent(response.data.content);
      alert('Citation inserted successfully!');
    } catch (err) {
      console.error('Failed to insert citation:', err);
      alert('Failed to insert citation');
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-xl text-gray-600">Loading draft...</div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Toolbar */}
      <div className="bg-white border-b border-gray-200 sticky top-0 z-10">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-xl font-bold text-gray-900">{draft?.title}</h1>
              <p className="text-sm text-gray-600">
                {draft?.document_type} • {draft?.case_type}
              </p>
            </div>

            <div className="flex items-center space-x-3">
              {/* Auto-save indicator */}
              {autoSaving && (
                <div className="flex items-center space-x-2 text-sm text-gray-600">
                  <div className="w-4 h-4 border-2 border-blue-600 border-t-transparent rounded-full animate-spin"></div>
                  <span>Saving...</span>
                </div>
              )}
              {!autoSaving && lastSaved && (
                <div className="flex items-center space-x-2 text-sm text-green-600">
                  <Check className="w-4 h-4" />
                  <span>Saved {new Date(lastSaved).toLocaleTimeString()}</span>
                </div>
              )}

              <button
                onClick={handleCopyToClipboard}
                className={`flex items-center space-x-2 px-4 py-2 rounded-lg transition ${
                  copied 
                    ? 'bg-green-600 text-white' 
                    : 'bg-gray-600 text-white hover:bg-gray-700'
                }`}
              >
                {copied ? (
                  <>
                    <Check className="w-4 h-4" />
                    <span>Copied!</span>
                  </>
                ) : (
                  <>
                    <Copy className="w-4 h-4" />
                    <span>Copy Text</span>
                  </>
                )}
              </button>

              <button
                onClick={() => handleAiAction('improve')}
                disabled={aiLoading}
                className="flex items-center space-x-2 px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition"
              >
                <Lightbulb className="w-4 h-4" />
                <span>AI Suggestions</span>
              </button>

              <button
                onClick={handleSave}
                disabled={saving}
                className="flex items-center space-x-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition"
              >
                <Save className="w-4 h-4" />
                <span>{saving ? 'Saving...' : 'Save'}</span>
              </button>

              <div className="relative group">
                <button className="flex items-center space-x-2 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition">
                  <Download className="w-4 h-4" />
                  <span>Export</span>
                </button>
                <div className="absolute right-0 mt-2 w-48 bg-white rounded-lg shadow-xl hidden group-hover:block z-10 border border-gray-200">
                  <button
                    onClick={handleDownloadPDF}
                    className="flex items-center space-x-2 w-full text-left px-4 py-3 hover:bg-green-50 rounded-t-lg transition"
                  >
                    <FileDown className="w-4 h-4 text-green-600" />
                    <div>
                      <div className="font-medium text-sm">Download PDF</div>
                      <div className="text-xs text-gray-500">Quick export</div>
                    </div>
                  </button>
                  <button
                    onClick={() => handleExport('docx')}
                    className="flex items-center space-x-2 w-full text-left px-4 py-3 hover:bg-blue-50 rounded-b-lg transition border-t"
                  >
                    <FileDown className="w-4 h-4 text-blue-600" />
                    <div>
                      <div className="font-medium text-sm">Export DOCX</div>
                      <div className="text-xs text-gray-500">Via backend</div>
                    </div>
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Tab Selector */}
        <div className="mb-4 flex space-x-2">
          <button
            onClick={() => {
              setShowQuality(false);
              setShowCaseLaw(false);
            }}
            className={`px-4 py-2 rounded-lg font-medium transition ${
              !showQuality && !showCaseLaw
                ? 'bg-purple-600 text-white'
                : 'bg-white text-gray-600 hover:bg-gray-100'
            }`}
          >
            <Lightbulb className="w-4 h-4 inline mr-2" />
            AI Assistant
          </button>
          <button
            onClick={() => {
              setShowQuality(true);
              setShowCaseLaw(false);
            }}
            className={`px-4 py-2 rounded-lg font-medium transition ${
              showQuality && !showCaseLaw
                ? 'bg-blue-600 text-white'
                : 'bg-white text-gray-600 hover:bg-gray-100'
            }`}
          >
            📊 Quality Score
          </button>
          <button
            onClick={() => {
              setShowQuality(false);
              setShowCaseLaw(true);
              if (caseLawResults.length === 0) {
                searchCaseLaw();
              }
            }}
            className={`px-4 py-2 rounded-lg font-medium transition ${
              showCaseLaw
                ? 'bg-gradient-to-r from-amber-500 to-amber-600 text-white'
                : 'bg-white text-gray-600 hover:bg-gray-100'
            }`}
          >
            <Scale className="w-4 h-4 inline mr-2" />
            Case Law
          </button>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Editor */}
          <div className="lg:col-span-2">
            <div className="bg-white rounded-lg shadow-md p-6">
              <textarea
                value={content}
                onChange={(e) => setContent(e.target.value)}
                onMouseUp={handleTextSelection}
                className="w-full h-[70vh] p-4 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 font-serif text-base leading-relaxed"
                style={{ resize: 'none' }}
              />
            </div>
          </div>

          {/* Right Sidebar - Quality Score, AI Assistant, or Case Law */}
          <div className="lg:col-span-1">
            {showQuality ? (
              <QualityScoreDashboard draftId={id} />
            ) : showCaseLaw ? (
              <div className="bg-white rounded-lg shadow-md p-6 sticky top-24">
                <h2 className="text-lg font-bold text-gray-900 mb-4 flex items-center space-x-2">
                  <Scale className="w-5 h-5 text-amber-600" />
                  <span>Relevant Case Law</span>
                </h2>

                {caseLawLoading ? (
                  <div className="flex items-center justify-center py-12">
                    <div className="w-8 h-8 border-3 border-amber-500 border-t-transparent rounded-full animate-spin"></div>
                  </div>
                ) : caseLawResults.length > 0 ? (
                  <div className="space-y-4 max-h-[calc(100vh-200px)] overflow-y-auto">
                    {caseLawResults.map((caseItem, index) => (
                      <div
                        key={index}
                        className="p-4 bg-gradient-to-br from-amber-50 to-yellow-50 border border-amber-200 rounded-lg hover:shadow-md transition"
                      >
                        <div className="flex items-start justify-between mb-2">
                          <h3 className="font-semibold text-gray-900 text-sm leading-tight flex-1">
                            {caseItem.title}
                          </h3>
                          <span className="text-xs bg-amber-600 text-white px-2 py-1 rounded ml-2">
                            {caseItem.relevance_score}%
                          </span>
                        </div>

                        <p className="text-xs text-amber-800 font-medium mb-2">
                          {caseItem.citation}
                        </p>

                        <p className="text-xs text-gray-600 mb-3 line-clamp-3">
                          {caseItem.excerpt}
                        </p>

                        <div className="flex items-center justify-between text-xs text-gray-500">
                          <span>{caseItem.court}</span>
                          <span>{caseItem.date}</span>
                        </div>

                        <div className="mt-3 flex gap-2">
                          <button
                            onClick={() => insertCitation(caseItem)}
                            className="flex-1 px-3 py-2 bg-amber-600 hover:bg-amber-700 text-white text-xs font-medium rounded transition"
                          >
                            Insert Citation
                          </button>
                          <a
                            href={caseItem.url}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="px-3 py-2 bg-white hover:bg-gray-50 text-gray-700 text-xs font-medium rounded border border-gray-300 transition flex items-center space-x-1"
                          >
                            <ExternalLink className="w-3 h-3" />
                            <span>View</span>
                          </a>
                        </div>
                      </div>
                    ))}
                  </div>
                ) : (
                  <div className="text-center py-12">
                    <Scale className="w-12 h-12 text-gray-400 mx-auto mb-3" />
                    <p className="text-gray-500 text-sm">No case law found</p>
                    <button
                      onClick={searchCaseLaw}
                      className="mt-4 px-4 py-2 bg-amber-600 hover:bg-amber-700 text-white text-sm rounded transition"
                    >
                      Search Again
                    </button>
                  </div>
                )}
              </div>
            ) : (
              <div className="bg-white rounded-lg shadow-md p-6 sticky top-24">
              <h2 className="text-lg font-bold text-gray-900 mb-4 flex items-center space-x-2">
                <Lightbulb className="w-5 h-5 text-yellow-500" />
                <span>AI Assistant</span>
              </h2>

              {selectedText && (
                <div className="mb-4 p-3 bg-blue-50 rounded-lg">
                  <p className="text-xs text-gray-600 mb-1">Selected Text:</p>
                  <p className="text-sm text-gray-800 italic line-clamp-3">
                    "{selectedText}"
                  </p>
                </div>
              )}

              <div className="space-y-2 mb-6">
                <button
                  onClick={() => handleAiAction('explain')}
                  disabled={aiLoading}
                  className="w-full px-4 py-2 bg-blue-100 text-blue-700 rounded-lg hover:bg-blue-200 transition text-sm font-medium"
                >
                  Explain Section
                </button>
                <button
                  onClick={() => handleAiAction('simplify')}
                  disabled={aiLoading}
                  className="w-full px-4 py-2 bg-green-100 text-green-700 rounded-lg hover:bg-green-200 transition text-sm font-medium"
                >
                  Simplify Language
                </button>
                <button
                  onClick={() => handleAiAction('rephrase')}
                  disabled={aiLoading}
                  className="w-full px-4 py-2 bg-purple-100 text-purple-700 rounded-lg hover:bg-purple-200 transition text-sm font-medium"
                >
                  Rephrase Legally
                </button>
                <button
                  onClick={() => handleAiAction('add_citation')}
                  disabled={aiLoading}
                  className="w-full px-4 py-2 bg-amber-100 text-amber-700 rounded-lg hover:bg-amber-200 transition text-sm font-medium"
                >
                  Find Citations
                </button>
              </div>

              {aiLoading && (
                <div className="text-center py-4">
                  <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mx-auto"></div>
                  <p className="text-sm text-gray-600 mt-2">AI Processing...</p>
                </div>
              )}

              {aiResult && (
                <div className="mt-4 p-4 bg-gray-50 rounded-lg border border-gray-200">
                  <h3 className="text-sm font-semibold text-gray-900 mb-2">AI Result:</h3>
                  <div className="text-sm text-gray-700 whitespace-pre-wrap">
                    {aiResult}
                  </div>
                </div>
              )}

              {/* Citations */}
              {draft?.citations && draft.citations.length > 0 && (
                <div className="mt-6 pt-6 border-t border-gray-200">
                  <h3 className="text-sm font-bold text-gray-900 mb-3 flex items-center space-x-2">
                    <BookOpen className="w-4 h-4" />
                    <span>Suggested Citations</span>
                  </h3>
                  <div className="space-y-2">
                    {draft.citations.map((citation, index) => (
                      <div key={index} className="p-2 bg-gray-50 rounded text-xs">
                        <p className="font-semibold text-gray-900">{citation.title}</p>
                        <p className="text-gray-600">{citation.citation}</p>
                      </div>
                    ))}
                  </div>
                </div>
              )}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default DraftEditor;
